### PR TITLE
uses img tag now

### LINKED ISSUE #28: Inquiry: <img> tag instead of markdown style
Hey N1ck, thanks for providing this awesome plugin

I wanted to ask if you'd be open for a PR that replaces the insertion of 

``

with

``

This way you can easily change the size of the gif with:

``

What do you think? 🙂

### PR DESCRIPTION
**Pull request by ritikbheda**
Resolves #28 

replaced `` by ``

### CODE REVIEW

**Comment by ritikbheda** [comment]
@e1himself @DATADEER,
as our discussion on #28

I tried adding the max-width but that did not really work.

adding max-width in this way is not allowed,
``

I also tried using style,
`` but that didn't work as well.

I then added a class and tried a few ways but didn't work as well. 

I think it is because of the GitHub coders made the `img` element style to be 100%. So now if we want to change it, we need to change the element style as whole and cannot target our GIF img tag. meaning all the images on the GitHub website will have that max-width property and we dont want to do that.

So as of now, we need to manually write the width property if the GIF is huge!

Do let me know your thoughts on this or any solutions to it if you have in mind.

**Comment by N1ck** [comment]
Awesome work, thank you very much for your contribution!




> So as of now, we need to manually write the width property if the GIF is huge!

I think that is fine, at least being an `img` tag gives people that control if they would like it.

**Review by N1ck — APPROVED** [review]

**Comment by e1himself** [comment]
Thank you! :heart:

**Comment by e1himself** [comment]
Looking forward for this update to be released :pray:

**Pull request merged**
